### ISSUE TITLE
QA 피드백 정리

### ISSUE THREAD

**Issue by tristanjung1006** [Team-Wash/Wash-Android#13]
## To-do
- [x] 플로팅 아이콘 위치 수정
- [x] 하단 여백 줄이기
- [x] 사진 조회시 Indicator 색 수정
- [x] 카메라 아이콘 크기 축소
- [x] 제거 버튼 투명도 올리기
- [ ] 문제 유형 색깔 부여
- [x] 키보드 숨기기 추가
- [x] 필수 선택 글자 추가
- [x] 버튼 클릭 반경 넓히기
