### ISSUE TITLE
[feature] API 연결

### ISSUE THREAD

**Issue by tristanjung1006** [Team-Wash/Wash-Android#18]
## To-do
- [ ] 문제 추가하기
- [x] 문제 조회하기
- [ ] 문제 수정하기
- [x] 문제 유형 선택하기
- [x] 문제 유형 추가하기
- [ ] AI 모델 탑재 YOLO 영역 인식 후 문제 추가
