### ISSUE TITLE
[feature] 문제풀이

### ISSUE THREAD

**Issue by tristanjung1006** [Team-Wash/Wash-Android#2]
## To-do
- [x] 문제풀이 지문 및 정답 추가 무한스크롤 가능한 RecyclerView
- [x] AI 풀이 채팅창 RecyclerView
- [x] 문제유형 선택 progressBar

https://github.com/user-attachments/assets/dcf4e453-3c74-4ab8-ab63-02a5a66edd90

https://github.com/user-attachments/assets/0c17da55-6598-4a87-9df2-446ff1d8c126

https://github.com/user-attachments/assets/5842540c-0b7b-476b-bb6d-21ac70795f45
