### ISSUE TITLE
[feature] 학습하기, 영역 선택 기능 구현, UI 수정

### ISSUE THREAD

**Issue by eldeoddt** [Team-Wash/Wash-Android#24]
## To-do
- 학습하기
  - [x] 학습하기 풀이 진척도 구현
  - [x] 지문 보기 리사이클러뷰로 수정
  - [x] 풀이 진척도 학습 완료 버튼 클릭 시 종료로 수정
  - [x] 폴더 position 리사이클러뷰에서 가져오도록 수정
  - [x] 폴더 오름차순 정렬
  - [x] 풀이 진척도 adapter 수정
  - [x] complete : 모든 문제의 풀이 진척도를 가져와서 계산
  - [x] 이미지 오류 수정
  - [x] 지문 보기 오류 수정
  - [x] 완료 페이지 api 오류 수정
  - [ ] 스와이프 시 인덱스 증가
- 노트 추가
  - [x] 사진 영역 추가 기능
  - [x] 영역 삭제
  - [x] 크롭 기능 구현
    - [x] 오류 수정
  - [x] 90도 회전 기능
  - [x] 앨범 선택 시 포토피커로 수정
  - [x] 바텀시트 위로 위치 수정
  - [x] 권한 코드 sdk에 따라 수정
  - [x] 다음 프래그먼트에 데이터 전달, 연결
  - [ ] 크롭 시 사각형 최소크기 지정

- api 
  - [x] 폴더 조회
  - [x] 전체 폴더 개수 조회
  - [x] 문제 조회
  - [x] 정답 post
  - [x] 풀이 진척도 get
