### ISSUE TITLE
[feature] 노트 추가 기능

### ISSUE THREAD

**Issue by eldeoddt** [Team-Wash/Wash-Android#3]
## To-do
- [x] ui 구현
- [x] 카메라 구현
- [x] 앨범 구현
- [ ] 영역 선택 
    - [x] ui 구현
    - [ ] 기능 구현
- [x] 디자인 구현
- [x] 카메라 문제 개수 선택 UI 구현
---
- [x] 학습하기 구현
- [x] 문제풀기
    - [x] 정답 확인 구현
    - [x] 완료 구현
    - [x] card image view 구현
    - [ ] drawer 구현
    - [x] card 상태 적용하기
    - [x] 애니메이션 추가
