### ISSUE TITLE
[fix] api 연결

### ISSUE THREAD

**Issue by eldeoddt** [Team-Wash/Wash-Android#40]
## To-do
- api
  - [x] 연결 확인
  - [x] 토큰 받아오도록 수정
- 노트 추가
  - [x] 사각형 최소 크기 지정
- 학습하기
  - [ ] 스와이프 시 인덱스 증가 
  - [x] 진척도 수신 오류 수정
