### ISSUE TITLE
20240829 마감내역

### ISSUE THREAD

**Issue by tristanjung1006** [Team-Wash/Wash-Android#59]
## To-do
- [x] 문제 추가 비즈니스 로직 변경
- [x] 문제 유형 건너뛰기 버그
- [x] 정답 입력시 추가문제 사진 업로드 가능하도록 변경
- [ ] 영역인식 AI 모델 탑재
- [x] 문제 상세정보 조회할 때만 AI 텍스트 추출하도록 변경
- [x] 문제 상세정보 조회
- [x] 문제 유형 태그 색깔 순차적 지정
- [x] 홈화면 폴더 목록 하위의 문제사진과 문제 상세정보 연동
- [x] AI 풀이 session key 연동
- [x] 이미지에서 문제 텍스트 추출 후 AI 풀이 자동화
- [x] 문제 편집 기능

## If I can afford to...
- 노트 목록 shimmer effect
- 문제 추가시 로딩 화면
- 유형 및 폴더 추가시 실시간 화면 로딩
- AI 채팅 로딩 표시
