### ISSUE TITLE
[fix] ui 추가, 로직 개선

### ISSUE THREAD

**Issue by eldeoddt** [Team-Wash/Wash-Android#60]
## To-do
- 학습하기
  - [x] 스와이프로 문제 이동
    - [x] 제스처 인식 개선
  - [x] 문제 이미지 확대, 축소
  - [x] 모든 문제 완료 시 자동으로 종료
  - [x] drawer ui 아이템 크기 조절, 사이즈 넓게 조절
  - [x] 마지막/추가 문제일 경우 버튼 invisible
  - [x] 폴더 불러오기 로직 개선
    - [x] 객체 리사이클러뷰로 로직 수정하기
  - [x] 문제id 순으로 정렬

- 노트 추가 
  - [x] 선택 영역 드래그 기능
    - [ ] 오프셋 보정
    - [ ] 바텀시트 인식 가능하도록 수정
